# fly.toml app configuration file generated for quizapplication on 2025-04-14T13:24:03Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "quizapplication"
primary_region = "fra"

[build]
dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
